db.go
Hi! I've just simplified sorting of ints. Please check this
=> using of sort.Ints instead pipe of sort and sort.IntSlice

datafile.go, datafile_test.go, db.go, examples/batch/put/main.go, examples/batch/read/main.go, examples/http/main.go, go.mod, go.sum, options.go, tx.go, tx_bptree.go, tx_bptree_test.go
* support data persistence
* discard mmap 
* modify EntryIdxMode
=> support data persistence && discard mmap && modify EntryIdxMode

README.md, bptree.go, bptree_test.go, go.mod, tx.go, tx_bptree.go, tx_bptree_test.go, tx_test.go
Add regexp search ability with PrefixSearchScan() function. Its need for my big project.
1. English readme
2. Tests added
3. Not forget about BPTSparse mode :)
=> Add PrefixSearchScan() with regexp search ability

db.go, db_test.go
=> repeated key merge fix

tx.go
For my usecase I don't want to be the current time to be the starting point for the expiration so I added this method.
=> allow put with timestamp

db.go, db_test.go, ds/list/list.go, ds/list/list_test.go, examples/list/main.go, tx.go, tx_list.go, tx_list_test.go
Mention from this link: https://github.com/xujiajun/nutsdb/issues/66
=> Fix: The LRem implementation is not consistent with the description. 

tx_bptree.go, tx_set.go
修改一些错误返回，这个项目有太多无法判断的错误返回，像bucket not found这种错误我是需要捕获并特殊处理的，但是根本没办法判断，现在我只修改了一部分，以后有时间我会再整理一下。
=> refactor: error

tx.go
=> fix(tx): close file before error check

.github/workflows/ci.yml
=> ci: add unit-test action

bptree.go, bptree_root_idx.go, bucket_meta.go, db.go, rwmanger_fileio.go, rwmanger_mmap.go, tar.go
=> fix: open file by variable

.github/workflows/ci.yml
=> ci(unit-test): fix unit-test

tar.go
=> Revert "close file before return err"

tx.go
1. Use a buffer to cache the entry list of "ready to write".
2. If file has enough space, the data is always written to the buffer..
4. If file is no more space for the new entry, then write cache data and
to rotate the new file.
5. If the last entry, to write the data to file.
=> optimize tx commit for batch write

tx.go, tx_bptree_test.go, tx_test.go
1. fix bug: the last entry should be committed status.
2. add the testcase
=> fix last entry status error

db_test.go, go.mod, go.sum, tx_test.go
1. import testify testcase
2. update some testcase
=> Update testcase: use testify test tools

ds/list/list_test.go, ds/set/set.go, ds/set/set_test.go
* Use testify lists and sets in test cases 
* Use the assertion of ElementsMatch, Subset, Contains and so on
* add some test cases
=> test: change list and set test with table driven test and  testify

bptree.go, bptree_test.go
=> update bptree unittest

ds/zset/sortedset_test.go
*  complete zset tests with testify
=> test: complete zset tests with testify

db_test.go, tx_bptree_test.go
import testify for testcase in tx_bptree_test.go
=> Update tx bptree testcase

bucket_meta_test.go, entry_test.go, tx_bucket_test.go
bucket_meta_test：remove files generated by the test
=> optimization tx_bucket_test and bucket_meta_test

tx_zset_test.go
*  test:complete tx_zset tests with testify
[issue 160](https://github.com/nutsdb/nutsdb/issues/160)
=> test:complete tx_zset tests with testify

bptree.go, errors.go, errors_test.go, go.mod, go.sum, inmemory/kv.go, inmemory/set.go, tx_bptree_test.go, tx_list.go, tx_set.go, tx_set_test.go
1. use `github.com/pkg/errors`.
2. optimize error management.
CLOSE: #161
=> errors: optimize error management

README-CN.md, README.md, db.go, ds/list/list.go, ds/list/list_test.go, examples/list/main.go, tx.go, tx_list.go, tx_list_test.go, utils.go, utils_test.go
feature: [A function that deletes the specified index (one or more)](https://github.com/nutsdb/nutsdb/issues/93)
=> add: [ISSUE#93] add LRemByIndex

ds/list/list.go, ds/list/list_test.go, inmemory/list.go, inmemory/list_test.go, tx_list.go
1. fix issue #177, and added a little more test code to `ds/list/list_teset.go`
2. test coverage done for `inmemory/list.go`
=> Bug fix and test coverage 0707

ds/list/list.go, ds/list/list_test.go, go.mod, go.sum
fix: https://github.com/nutsdb/nutsdb/issues/203
=> fix:   MInInt function compatible with 32-bit operating systems 

bptree.go, inmemory/db_test.go, inmemory/kv.go
1、support list all key of bucket in memory mode #200 
2、Fix the bug of range method in memory mode
=> feat: list all key of bucket in memory mode

examples/inmemory/main.go, inmemory/db_test.go, inmemory/kv.go
add PrefixScan in memory mode #188
=> feat: add PrefixScan in memory mode

fd_manager.go
changing the lock to be one of property of the structure can make the code more readable.
=> change the lock to prototy

recovery_reader.go, recovery_reader_test.go
Adding a test of readEntry() and refactoring readEntry(). using ReadFull () instead of Read ().
=> Adding a test of readEntry() and refacting readEntry()

ds/list/list_test.go, ds/set/set_test.go
codes not covered in ds/zset/sortedset.go is for implementation purpose, it's time consuming to track, so omit it for now.
=> test coverage improvement

errors_test.go
adding a test for `IsKeyEmpty` func  in  `github.com/xujiajun/nutsdb/errors.go:26:`
=> adding a test for IsKeyEmpty func  in  `github.com/xujiajun/nutsdb/errors.go:26:`

db.go
use file revovery reader in merge
=> Use file recovery in merge

bptree_test.go
Add test for `ToBinary` in `bptree.go`, refer to Issues #238
=> Add test for `ToBinary` in `bptree.go`

db.go, ds/list/list.go, tx.go, tx_list.go, tx_list_test.go
user can use ExpireList to set ttl for list
=> feat:support ttl function for list

errors_test.go
Add test for bucket in `errors.go`, refer to issues #238
=> Add test for bucket in `errors.go`

db.go, examples/basic/main.go, examples/batch/concurrence/main.go, examples/batch/put/main.go, examples/batch/read/main.go, examples/bucket/main.go, examples/http/main.go, examples/inmemory/main.go, examples/iterator/main.go, examples/list/main.go, examples/set/main.go, examples/sortedSet/main.go, go.mod, inmemory/db_test.go, inmemory/kv.go, inmemory/list.go, inmemory/list_test.go, inmemory/set.go, inmemory/set_test.go, inmemory/shard.go, inmemory/zset.go, inmemory/zset_test.go, tx.go, tx_list.go, tx_set.go, tx_zset.go
change the go mod module name  xujiajun/nutsdb -> nutsdb/nutsdb
=> change the xujiajun/nutsdb -> nutsdb/nutsdb

errors.go
=> fix: issue (#288)

ds/list/list.go, ds/list/list_test.go
Fix a bug reported in Issues #280
=> Fix issues #280: LIST "start or end error" after deleting the last item

errors_test.go
Add some tests for IsDBClosed, IsPrefixScan and IsPrefixSearchScan in nutsdb/errors.go
=> test: add tests for IsDBClosed, IsPrefixScan and IsPrefixSearchScan

tx_test.go
Adds `TestTx_PutWithTimestamp` in `tx_test.go`, refer to issues https://github.com/nutsdb/nutsdb/issues/238
=> Add test for `PutWithTimestamp` in `tx.go`

README.md
=> docs(readme): format code

ds/list/list.go, tx_list.go, tx_list_test.go
get remaining time to live of a key that has a timeout ,see https://github.com/nutsdb/nutsdb/issues/304
=> feat:add GetListTTL

tx_bptree.go
delete a repeat error validation logic
=> [ref]delete a repeat error validation logic

datafile_test.go, db.go, entry.go, entry_test.go, inmemory/kv.go, recovery_reader_test.go, tx.go, tx_bptree.go
Seems it's unreasonable that bucket value as a property in meta, so move it into entry in this PR.
=> [ref]make bucket value as a property in entry

datafile.go, entry.go, recovery_reader.go
move crc property into meta struct
=> [ref]move crc property into meta struct

datafile_test.go, entry.go, entry_test.go, recovery_reader_test.go
detele the position porperty of entry struct
=> [ref]detele the position porperty of entry struct

db.go, entry.go
refactor the method named isFilterEntry and move it to Entry level
=> [ref]refactor method isFilterEntry

db.go
add function return the status of DB
=> [ref]add function return the status of DB

db_test.go, tx.go, tx_bptree.go
fix delete non exist will not raise error bug
=> [bug]fix delete non exist will not raise error bug

tx.go
rebuild the status management code
=> [ref]rebuild the status management code

entry.go, tx.go
put the validation logic into Entry layer.
=> [ref]Refactor entry length check

db.go
fix ignore bucket when db recovering
=> [bug]fix ignore bucket when db recovering

db.go, index.go
just move the index-related structure into the rightful space.
=> [ref]just move the index structure in a rightful space

go.mod, go.sum
fix some issue in go mod config, run the go mod tidy in local
=> [ref]fix some issue in go mod config

db.go, db_test.go, index.go, tx.go, tx_bucket.go, tx_list.go
rebuild the index module for index struct, my intent for this MR is warp all index struct into a single module.
=> [ref] rebuild the index moudle for index struct

db.go, index.go, tx.go
rebuild the function addList in List Index module.
=> rebuild the add function in list index

bptree_test.go, db.go, entry.go, tx.go
rebuild the way to create hint object
=> [ref]rebuild the way to create hint object

entry.go, utils.go
=> [ref]rebuild isFilter function

bptree_test.go, datafile.go, db.go, entry.go, recovery_reader_test.go, tx.go, utils_test.go
rebuild the way to new Entry Object
=> [ref]rebuild the way to new Entry Object

bptree.go, bptree_test.go, db.go, entry.go, record.go
rebuilt the way to new Record object
=> [ref]rebuilt the way to new Record object

options_test.go
=> test: test WithRWMode

rwmanager_mmap_test.go
Add test for rwmanager mmap `Sync`, `Close`, `WriteAt`.
=> test: test rwmanager mmap

bptree.go, bptree_test.go, db_test.go
1. add unit test for ErrWhenBuildListIdx  func in db.go
2. optimize enqueue func in bptree.go and add unit test for it
=> add test case for ErrWhenBuildListIdx func in db.go and optimize enqueue func in bptree.go and add test case

db.go, db_test.go, fd_manager_test.go, go.mod, go.sum, options_test.go
I implemented file lock by use [gofrs/flock](https://github.com/gofrs/flock).
=> feat: implement file lock

db_test.go, test_utils.go, utils.go
This is a **WIP** pr.
I made some modifications to have each test case use its own database instance, and I encapsulated some database operations to avoid redundant code. Is this refactoring feasible?
=> test: rebuild unit tests in db_test.go(issue#374, task 4)

db.go, iterator.go, tx.go, tx_bptree.go, utils.go
Small scope refactoring code，move some common func to utils.go from db.go
=>  Small scope refactoring code:move some util func to utils.go from db.go

db.go, db_test.go, options.go, options_test.go, tx.go
Add custom error handler for an error that occur during transaction. #354
=> chore: add error handler for error occurred during transaction

db.go, db_test.go, entry.go, entry_test.go, options.go, options_test.go, tx_bptree.go, utils.go, utils_test.go
Refactor func to sort key and add custom comparator. #373
=> feat: add custom comparator

batch.go, batch_test.go, db.go, examples/batch/put/main.go, options.go, options_test.go, throttle.go, tx.go, value.go
1. add batch write(contains batch write and batch delete)
2. add batch write unit test
=> add batch write

merge.go
I forgot remove code of printing log🤣.
=> style: remove useless code

db.go
use goto refactor recovery logic, for making the logic here more clarify.
=> use goto refactor recovery logic

db.go, tx.go, tx_test.go, tx_tree.go
delete the map db.committedTxIds, it will not needed any more
=> [ref]delete the map db.committedTxIds, it will not needed any more

db.go
rebuild the recovery logic, and delete the unconfirmedRecordList for making the recovery pipeline more fast.
=> [ref]rebuild the recovery logic, and delete the unconfirmedRecordList

db.go
delete getActiveFileWriteOff func
=> delete getActiveFileWriteOff func

db.go
rebuild the error handling logic in recovery
=> [ref] rebuild the error handling logic in recovery

db.go, db_error.go
move the errors in db file to another seperated file.
=> [ref] move the errors in db file to another seperated file.

db_test.go, tx_set_test.go
=> test: refactor `tx_set_test`

db_test.go, tx_bucket_test.go
=> test: refactor `tx_bucket_test`

tx.go, tx_error.go
move the tx error to seperated file
=> [ref]move the tx error to seperated file

db_test.go
=> fix: deadlock when test failed

datafile.go, entity_utils.go, entity_utils_test.go, entry.go
add a function that can automatically get the disk size of meta header
=> [ref]add a function that can automatically get the disk size of meta header

bucket_manager_test.go, db_test.go, tx_bucket.go
=> add more api for bucket

db_test.go, tx_btree.go, tx_btree_test.go
=> feat: add GetMaxKey and GetMinKey for kv type

bucket.go, tx.go
add the definition of bucketStatus and add the calculation logic for it.
=> [feat]add the definition of bucketStatus and add the calculation logic for it.

db_test.go, tx_btree.go, tx_btree_test.go
This PR adds suggest new APIs (SETEX and SETNX) in #517 
**Note: #526  this bug has to be fixed before merging this.**
=> feat : add PutIfExists(SETEX) and PutIfNotExists(SETNX) APIs

index.go, tx_list.go, tx_zset.go
Hi Team,
This fixes https://github.com/nutsdb/nutsdb/issues/536.
Please see the example I've provided in https://github.com/nutsdb/nutsdb/issues/536
Kind Regards,
Yudha
=> fix: check the list map instead of writing it

db_test.go, docs/user_guides/use-kv-pair.md, examples/basic/main.go, tx_btree.go, tx_btree_test.go
This PR is related to Issue https://github.com/nutsdb/nutsdb/issues/517
- add StrLen()
=> feat: add getlen to retrieve length of the value by key

db_test.go, docs/user_guides/use-kv-pair.md, examples/basic/main.go, tx_btree.go, tx_btree_test.go
Hi this PR is related to the issue
- add GetSet() to set a new value and return an old value
=> feat: add getset method

db_test.go, tx_zset_test.go
Related issue: #503 
I completed this unit test by referring to [TestTx_SKeys](https://github.com/nutsdb/nutsdb/blob/f7c4a82b75c2f437feccd9499ca1242a169cd858/tx_set_test.go#L401).
=> test: add test for ZSet.ZKeys

db_test.go, docs/user_guides/use-kv-pair.md, examples/basic/main.go, tx_btree.go, tx_btree_test.go
* implement ttl and persist
* docs for ttl, persist, put if exists, and put if not exists
Implements APIs for #517
=> feat: implements ttl and persist

db_test.go, tx_list.go, tx_list_test.go
This PR Relate with issues : https://github.com/nutsdb/nutsdb/issues/548
- add check generateNewKey() on each loop
=> fix: cant insert multiple values at list

tx.go
=> [ref]change the pendinglist to map structure

README-CN.md, README.md
=> docs: add contributors images.

db_test.go, tx_zset_test.go
- Test: Add unit test for function `ZPeekMin` metioned in #503
=> test(zset): Add unit test for ZPeekMin

tx.go
=> [BugFix]fix the bug in tx visibility

pending.go, tx.go
rebuild the data structure of pending BTree and Pending Write Entires
=> [ref]rebuild the data structure of pending BTree and Pending Write Entires

bucket.go, pending.go, tx.go, tx_btree.go
[ref]rebuild the code for pendingList and pendingBucket
=> [ref]rebuild the code for pendingList and pendingBucket

const.go
=> Fix MAX_SIZE on 64bit

tx_zset_test.go
This PR is related with issue #503 
- add unit test for ZRangeByScore
=> test(zset): Add unit test for ZRangeByScore

bucket_manager.go
https://github.com/nutsdb/nutsdb/issues/588
=> fix new bucket id start from 1 after reopen db

tx_list.go
=> fix(tx_list.go): RPush uses LPush's Flag

merge_test.go, tx.go, tx_list.go
=> fix(issue 609):  ensure the existence and correctness of list indices
